# -*- coding: utf-8 -*-
# src/refactoring_analyzer/refactoring_analyzer.py

"""
リファクタリング分析統合モジュール - メインコーディネーター
"""

import os
import json
from datetime import datetime
from typing import Dict, List, Any, Optional

# サブパッケージからのインポート
from .analyzers import (
    CSharpRefactoringAnalyzer,
    PythonRefactoringAnalyzer,
    JavaScriptRefactoringAnalyzer
)
from .metrics import (
    QualityMetricsCalculator,
    ImpactScopeAnalyzer,
    RecommendationEngine,
    RefactoringSuggestionEngine,
    RefactoringJSONReporter,
    RefactoringHTMLReporter
)
from .detectors import (
    LongMethodDetector,
    DuplicateCodeDetector,
    ComplexConditionDetector,
    GodClassDetector
)

class RefactoringAnalyzer:
    """リファクタリング分析の中心的なコントローラー"""
    
    def __init__(self, workspace_root: str = ".", log_manager=None, action_executor=None):
        self.workspace_root = workspace_root
        self.log_manager = log_manager
        self.action_executor = action_executor
        self.config = self._load_refactoring_config()
        self.analyzers = {
            "csharp": CSharpRefactoringAnalyzer(self.config.get("csharp", {}), self.action_executor),
            "python": PythonRefactoringAnalyzer(self.config.get("python", {})),
            "javascript": JavaScriptRefactoringAnalyzer(self.config.get("javascript", {}))
        }
    
    def _load_refactoring_config(self) -> Dict[str, Any]:
        """リファクタリング設定を読み込む"""
        config_path = os.path.join(self.workspace_root, "resources", "refactoring_config.json")
        
        default_config = {
            "project_profiles": {},
            "exclusion_rules": {
                "file_patterns": ["*.Designer.cs", "*.g.cs", "*.generated.cs"],
                "directory_patterns": ["bin", "obj", "node_modules", "__pycache__", ".git"],
                "content_patterns": ["// <auto-generated", "# Generated by"]
            },
            "csharp": {
                "smell_thresholds": {
                    "long_method_lines": 20,
                    "cyclomatic_complexity": 10,
                    "parameter_count": 5,
                    "class_line_count": 300,
                    "god_class_method_count": 15
                },
                "auto_fix_enabled": ["rename_variable", "extract_constant"],
                "safety_checks": ["test_coverage", "dependency_analysis"]
            },
            "python": {
                "smell_thresholds": {
                    "long_method_lines": 25,
                    "cyclomatic_complexity": 8,
                    "parameter_count": 4
                },
                "tools": ["pylint", "flake8"]
            },
            "javascript": {
                "smell_thresholds": {
                    "long_function_lines": 15,
                    "cyclomatic_complexity": 6,
                    "parameter_count": 3
                },
                "tools": ["eslint"]
            }
        }
        
        try:
            if os.path.exists(config_path):
                with open(config_path, 'r', encoding='utf-8') as f:
                    loaded_config = json.load(f)
                for key in default_config:
                    if key in loaded_config:
                        if isinstance(loaded_config[key], dict) and isinstance(default_config[key], dict):
                            self._deep_merge_config(default_config[key], loaded_config[key])
                        else:
                            default_config[key] = loaded_config[key]
                return default_config
        except Exception as e:
            if self.log_manager:
                self.log_manager.log_event("refactoring_config_error", {"error": str(e)}, "WARNING")
        
        return default_config
    
    def _deep_merge_config(self, base_config: Dict[str, Any], override_config: Dict[str, Any]) -> None:
        """設定の深いマージを実行"""
        for key, value in override_config.items():
            if key in base_config and isinstance(value, dict) and isinstance(base_config[key], dict):
                self._deep_merge_config(base_config[key], value)
            else:
                base_config[key] = value

    def apply_profile(self, profile_name: str) -> bool:
        """プロファイル設定を適用"""
        profile = self.config.get("project_profiles", {}).get(profile_name)
        if not profile:
            return False
        
        self._deep_merge_config(self.config, profile)
        return True

    def analyze_project(self, project_path: str, language: str, options: Dict[str, Any] = None) -> Dict[str, Any]:
        """プロジェクトのリファクタリング分析を実行"""
        options = options or {}
        
        try:
            if self.log_manager:
                self.log_manager.log_event("refactoring_analysis_start", {
                    "project_path": project_path,
                    "language": language,
                    "options": options
                })
            
            if not os.path.exists(project_path):
                error_msg = f"プロジェクトパスが存在しません: {project_path}"
                return {"status": "error", "message": error_msg}
            
            # 1. コードスメル検出
            smell_result = self._detect_code_smells(project_path, language, options)
            if smell_result["status"] != "success":
                return smell_result
            
            # 2. リファクタリング提案生成
            suggestions = self._generate_refactoring_suggestions(smell_result["code_smells"], language, options)
            
            # 3. 品質メトリクス計算
            roslyn_analysis_data = smell_result.get("roslyn_analysis") if language == "csharp" else None
            quality_metrics = self._calculate_quality_metrics(project_path, language, smell_result["code_smells"], roslyn_analysis_data)
            
            # 4. 影響範囲分析
            impact_analysis = self._analyze_impact_scope(suggestions, project_path, language, roslyn_analysis_data)
            
            # 5. 推奨事項生成
            recommendations = self._generate_recommendations(smell_result, suggestions, quality_metrics)
            
            # 6. レポート生成
            reports = self._generate_reports(smell_result, suggestions, quality_metrics, recommendations, options)
            
            # 7. 結果統合
            result = {
                "status": "success",
                "project_path": project_path,
                "language": language,
                "analysis_summary": self._create_analysis_summary(smell_result["code_smells"], suggestions),
                "code_smells": smell_result["code_smells"],
                "refactoring_suggestions": suggestions,
                "quality_metrics": quality_metrics,
                "impact_analysis": impact_analysis,
                "recommendations": recommendations,
                "reports": reports,
                "timestamp": datetime.now().isoformat()
            }
            
            return result
        except Exception as e:
            return {"status": "error", "message": str(e)}
    
    def _detect_code_smells(self, project_path: str, language: str, options: Dict[str, Any]) -> Dict[str, Any]:
        """コードスメルを検出"""
        if language not in self.analyzers:
            return {"status": "error", "message": f"サポートされていない言語です: {language}"}
        
        return self.analyzers[language].detect_smells(project_path, options)
    
    def _generate_refactoring_suggestions(self, code_smells: List[Dict[str, Any]], language: str, options: Dict[str, Any]) -> List[Dict[str, Any]]:
        """リファクタリング提案を生成"""
        suggestion_engine = RefactoringSuggestionEngine(language, self.config.get(language, {}))
        return suggestion_engine.generate_suggestions(code_smells, options)
    
    def _calculate_quality_metrics(self, project_path: str, language: str, code_smells: List[Dict[str, Any]], roslyn_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """品質メトリクスを計算"""
        metrics_calculator = QualityMetricsCalculator(language)
        return metrics_calculator.calculate(project_path, code_smells, roslyn_data)
    
    def _analyze_impact_scope(self, suggestions: List[Dict[str, Any]], project_path: str, language: str, roslyn_analysis_results: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """影響範囲を分析"""
        impact_analyzer = ImpactScopeAnalyzer(language, roslyn_analysis_results)
        return impact_analyzer.analyze(suggestions, project_path)
    
    def _generate_recommendations(self, smell_result: Dict[str, Any], suggestions: List[Dict[str, Any]], quality_metrics: Dict[str, Any]) -> List[Dict[str, Any]]:
        """推奨事項を生成"""
        recommendation_engine = RecommendationEngine()
        return recommendation_engine.generate(smell_result, suggestions, quality_metrics)
    
    def _generate_reports(self, smell_result: Dict[str, Any], suggestions: List[Dict[str, Any]], 
                          quality_metrics: Dict[str, Any], recommendations: List[Dict[str, Any]], 
                          options: Dict[str, Any]) -> Dict[str, str]:
        """レポートを生成"""
        output_formats = options.get("output_formats", ["json", "html"])
        reports = {}
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_dir = os.path.join(self.workspace_root, "refactoring_reports")
        os.makedirs(report_dir, exist_ok=True)
        
        if "json" in output_formats:
            json_path = os.path.join(report_dir, f"analysis_{timestamp}.json")
            RefactoringJSONReporter().generate(json_path, smell_result, suggestions, quality_metrics, recommendations)
            reports["detailed_report"] = json_path
        
        if "html" in output_formats:
            html_path = os.path.join(report_dir, f"analysis_{timestamp}.html")
            RefactoringHTMLReporter().generate(html_path, smell_result, suggestions, quality_metrics, recommendations)
            reports["summary_report"] = html_path
            
        return reports

    def _create_analysis_summary(self, code_smells: List[Dict[str, Any]], suggestions: List[Dict[str, Any]]) -> Dict[str, Any]:
        """分析サマリーを作成"""
        severity_counts = {"high": 0, "medium": 0, "low": 0}
        for smell in code_smells:
            severity = smell.get("severity", "medium")
            if severity in severity_counts:
                severity_counts[severity] += 1
        
        auto_fixable_count = sum(1 for sug in suggestions if sug.get("auto_fixable", False))
        
        return {
            "total_smells": len(code_smells),
            "high_priority": severity_counts["high"],
            "medium_priority": severity_counts["medium"],
            "low_priority": severity_counts["low"],
            "auto_fixable": auto_fixable_count
        }
