INTENT_ANALYZE_COVERAGE_GAPS = "ANALYZE_COVERAGE_GAPS"
INTENT_ANALYZE_REFACTORING = "ANALYZE_REFACTORING"
INTENT_ANALYZE_TEST_FAILURE = "ANALYZE_TEST_FAILURE"
INTENT_APPLY_CODE_FIX = "APPLY_CODE_FIX"
INTENT_APPLY_REFACTORING = "APPLY_REFACTORING"
INTENT_BACKUP_AND_DELETE = "BACKUP_AND_DELETE"
INTENT_CMD_RUN = "CMD_RUN"
INTENT_CONFIGURE_QUALITY_GATES = "CONFIGURE_QUALITY_GATES"
INTENT_CS_ANALYZE = "CS_ANALYZE"
INTENT_CS_IMPACT_SCOPE = "CS_IMPACT_SCOPE"
INTENT_CS_QUERY_ANALYSIS = "CS_QUERY_ANALYSIS"
INTENT_CS_TEST_RUN = "CS_TEST_RUN"
INTENT_DOC_GEN = "DOC_GEN"
INTENT_DOC_REFINE = "DOC_REFINE"
INTENT_EXECUTE_GOAL_DRIVEN_TDD = "EXECUTE_GOAL_DRIVEN_TDD"
INTENT_FILE_APPEND = "FILE_APPEND"
INTENT_FILE_COPY = "FILE_COPY"
INTENT_FILE_CREATE = "FILE_CREATE"
INTENT_FILE_DELETE = "FILE_DELETE"
INTENT_FILE_MOVE = "FILE_MOVE"
INTENT_FILE_READ = "FILE_READ"
INTENT_FILE_WRITE = "FILE_WRITE"
INTENT_GENERATE_PIPELINE_CONFIG = "GENERATE_PIPELINE_CONFIG"
INTENT_GENERATE_COVERAGE_REPORT = "GENERATE_COVERAGE_REPORT"
INTENT_GENERATE_TESTS = "GENERATE_TESTS"
INTENT_GET_CWD = "GET_CWD"
INTENT_LIST_DIR = "LIST_DIR"
INTENT_MANAGE_KNOWLEDGE = "MANAGE_KNOWLEDGE"
INTENT_MEASURE_COVERAGE = "MEASURE_COVERAGE"
INTENT_PROVIDE_CONTENT = "PROVIDE_CONTENT"
INTENT_PROVIDE_CRITERIA = "PROVIDE_CRITERIA"
INTENT_READ_AND_CREATE = "READ_AND_CREATE"
INTENT_RECOVERY_FROM_TEST_FAILURE = "RECOVERY_FROM_TEST_FAILURE"
INTENT_REVERSE_DICTIONARY_SEARCH = "REVERSE_DICTIONARY_SEARCH"
INTENT_RUN_LEARNING_CYCLE = "RUN_LEARNING_CYCLE"
INTENT_SET_METHOD_NAME = "SET_METHOD_NAME"
INTENT_SETUP_CICD = "SETUP_CICD"
INTENT_SUGGEST_REFACTORING = "SUGGEST_REFACTORING"

FILE_MUTATION_INTENTS = (
    INTENT_FILE_CREATE,
    INTENT_FILE_MOVE,
    INTENT_FILE_COPY,
)

PROJECT_LANGUAGE_DEFAULT_INTENTS = (
    INTENT_MEASURE_COVERAGE,
    INTENT_ANALYZE_COVERAGE_GAPS,
    INTENT_GENERATE_COVERAGE_REPORT,
    INTENT_ANALYZE_REFACTORING,
    INTENT_SUGGEST_REFACTORING,
)
