# -*- coding: utf-8 -*-
"""Shared constants for explicit approval / rejection flows."""

INTENT_CLARIFICATION_RESPONSE = "CLARIFICATION_RESPONSE"
INTENT_AGREE = "AGREE"
INTENT_DISAGREE = "DISAGREE"

RESPONSE_APPROVED = INTENT_AGREE
RESPONSE_REJECTED = INTENT_DISAGREE

STATE_AGREED = "AGREED"
STATE_DISAGREED = "DISAGREED"
