INTENT_BYE = "BYE"
INTENT_CANCEL_TASK = "CANCEL_TASK"
INTENT_CAPABILITY = "CAPABILITY"
INTENT_CORRECTION = "CORRECTION"
INTENT_DEFINITION = "DEFINITION"
INTENT_EMOTIVE = "EMOTIVE"
INTENT_FEEDBACK = "FEEDBACK"
INTENT_FEEDBACK_RECEIVED = "FEEDBACK_RECEIVED"
INTENT_GENERAL = "GENERAL"
INTENT_GREETING = "GREETING"
INTENT_NO_INTENT = "NO_INTENT"
INTENT_PERSONAL_Q = "PERSONAL_Q"
INTENT_RETRY = "RETRY"
INTENT_SMALLTALK = "SMALLTALK"
INTENT_TIME = "TIME"
INTENT_WEATHER = "WEATHER"

CONVERSATIONAL_INTENTS = (
    INTENT_GREETING,
    INTENT_PERSONAL_Q,
    INTENT_EMOTIVE,
    INTENT_SMALLTALK,
    INTENT_FEEDBACK,
    INTENT_WEATHER,
    INTENT_TIME,
    INTENT_CAPABILITY,
    INTENT_BYE,
    INTENT_DEFINITION,
    INTENT_GENERAL,
)

TASK_INTERRUPTION_INTENTS = CONVERSATIONAL_INTENTS + (INTENT_NO_INTENT,)
